ARG  NOTEBOOK_VERSION
FROM ghcr.io/dodas-ts/notebook:${NOTEBOOK_VERSION}-base

USER root

WORKDIR /tmp

RUN apt-get install -y curl

RUN curl -fsSL https://get.htcondor.org | /bin/bash -s -- --no-dry-run

COPY ./condor_config /etc/condor/condor_config

WORKDIR /opt/workspace
