ARG  NOTEBOOK_VERSION
FROM ghcr.io/dodas-ts/notebook:${NOTEBOOK_VERSION}-htc
USER root

#RUN pip install 

COPY ./jupyterhub-singleuser.sh /usr/local/bin/jupyterhub-singleuser.sh
RUN chmod +x /usr/local/bin/jupyterhub-singleuser.sh
WORKDIR /opt/workspace
