language: generic

install:
    - wget https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl -O /tmp/kubectl
    - chmod +x /tmp/kubectl
    - wget http://storage.googleapis.com/kubernetes-helm/helm-${HELM_VERSION}-linux-amd64.tar.gz -O /tmp/helm.tar.gz
    - tar xzf /tmp/helm.tar.gz -C /tmp --strip-components=1
    - chmod +x /tmp/helm
    - export PATH=$PATH:/tmp

before_script:
    - helm init --client-only

script:
    make

deploy: # Deploy documentation to Github in the gh_pages branch
    provider: pages
    skip_cleanup: true
    github_token: $token
