# Default values for cachingondemand.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


# ExternalIps to be used for service exposition
externalIP:
    enabled: true
    ip: 192.168.65.3 

# Spark master deployment and service configuration values
master:
    name: master
    image: cloudpg/spark-py
    imageTag: dodas-2.4.3-bigdl
    replicas: 1
    component: spark-master
    cpu: 100m
    memory: 1024Mi
    servicePort: 7077
    containerPort: 7077
    # Set Master JVM memory. Default 1g
    # DaemonMemory: 1g
    serviceType: NodePort
    jupyter:
        nodePort: 30888

# WebUi service configuration values
webUi:
  name: webui
  servicePort: 8080
  containerPort: 8080
  nodePort: 30808
  serviceType: NodePort

# Where to store jupyter data
hostPath: 
    path: /tmp
