apiVersion: apps/v1
kind: Deployment
metadata:
  name: daskssh
  labels:
    app.kubernetes.io/name: daskssh
spec:
  template:
    metadata:
      labels:
        app.kubernetes.io/name: daskssh 
    spec:
      priorityClassName: system-node-critical
      containers:
      - name: redis 
        resources:
          requests:
            memory: {{ .Values.ssh-forwader.redis.requests.memory }}
            cpu: {{ .Values.ssh-forwader.redis.requests.cpu }}
          limits:
            memory: {{ .Values.ssh-forwader.redis.limits.memory }}
            cpu: {{ .Values.ssh-forwader.redis.limits.cpu }}
        imagePullPolicy: {{ .Values.ssh-forwader.redis.image.pullPolicy }}
        image: "{{ .Values.ssh-forwader.redis.image.name }}:{{ .Values.ssh-forwader.redis.image.tag }}"
        volumeMounts: []
      - name: daskssh 
        resources:
          requests:
            memory: {{ .Values.ssh-forwader.sshFWD.requests.memory }}
            cpu: {{ .Values.ssh-forwader.sshFWD.requests.cpu }}
          limits:
            memory: {{ .Values.ssh-forwader.sshFWD.limits.memory }}
            cpu: {{ .Values.ssh-forwader.sshFWD.limits.cpu }}
        imagePullPolicy: {{ .Values.ssh-forwader.sshFWD.image.pullPolicy }}
        image: "{{ .Values.ssh-forwader.sshFWD.image.name }}:{{ .Values.ssh-forwader.sshFWD.image.tag | default .Chart.AppVersion }}"
      - name: listener 
        resources:
          requests:
            memory: {{ .Values.ssh-forwader.sshListener.requests.memory }}
            cpu: {{ .Values.ssh-forwader.sshListener.requests.cpu }}
          limits:
            memory: {{ .Values.ssh-forwader.sshListener.limits.memory }}
            cpu: {{ .Values.ssh-forwader.sshListener.limits.cpu }}
        imagePullPolicy: {{ .Values.ssh-forwader.sshListener.image.pullPolicy }}
        image: "{{ .Values.ssh-forwader.sshListener.image.name }}:{{ .Values.ssh-forwader.sshListener.image.tag | default .Chart.AppVersion }}"
      volumes:
  selector:
    matchLabels:
      app.kubernetes.io/name: daskssh 
  

  replicas: 1
  strategy:
    type: Recreate