apiVersion: v1 
kind: Service 
metadata:
  name: sshFWD 
spec:
  type: NodePort 
  ports:
    - port: 8022 
      nodePort: {{ .Values.ssh-forwarder.sshFWD.nodePort }}
      protocol: TCP
      name: daskssh 
  selector:
    app.kubernetes.io/name: daskssh

---

apiVersion: v1 
kind: Service 
metadata:
  name: sshListener 
spec:
  type: ClusterIP 
  clusterIP: 
  ports:
    - port: 8122 
      targetPort: 8122
      protocol: TCP
      name: listener 
  selector:
    app.kubernetes.io/name: daskssh