{{- if or .Values.master.enabled .Values.schedd.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: submission-endpoint
stringData:
  collector-url: "{{ .Values.master.publicIP }}.myip.cloud.infn.it:30618"
  schedd-url: "{{ .Values.master.publicIP }}.myip.cloud.infn.it"
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-key-pair
stringData:
  tls.crt: |
                                -----BEGIN CERTIFICATE-----
                                MIIDYTCCAkmgAwIBAgIUXem+C2mwPsNvutsxruSDGmJmtLMwDQYJKoZIhvcNAQEL
                                BQAwQDELMAkGA1UEBhMCSVQxEDAOBgNVBAgMB1BlcnVnaWExEDAOBgNVBAcMB1Bl
                                cnVnaWExDTALBgNVBAoMBElORk4wHhcNMjYwNTA1MDkxNTM5WhcNMzYxMDI0MDkx
                                NTM5WjBAMQswCQYDVQQGEwJJVDEQMA4GA1UECAwHUGVydWdpYTEQMA4GA1UEBwwH
                                UGVydWdpYTENMAsGA1UECgwESU5GTjCCASIwDQYJKoZIhvcNAQEBBQADggEPADCC
                                AQoCggEBAN4EHUg34iFUCsltuGVpUNrp+IKD4PU8Vss3B1Se3I5jfRmsWk/kgFTE
                                j8z2Ja1clr1cK6DJDqVP7yz+SuCMy/Oz3kHEfzn+7qSnL+gJpW+hGDRWU6QGiZrK
                                RIFI7ybGsH4J3I+KKeWt1fIO5K3jr0XAAinpoNRlwgqL8yW4PthEg6m5voEerAcg
                                efGlKqvuwKsJMMCFltnjm2nP8Bu/fi6pG/DC9Wyua6S2KnGDxDmHBEnx+jl6Sz6F
                                kUHMiI7sffoCtLUVAJr72Y+YfyifLCOlHJ8FInO/uoEU+BmL4m4ueLQu1N9Xc+5K
                                4u3/UiO3oZ3O2urBL1jFQZZOIJxnWcUCAwEAAaNTMFEwHQYDVR0OBBYEFOYY+l7l
                                RTQbtMtn9aw5O3uuyFuIMB8GA1UdIwQYMBaAFOYY+l7lRTQbtMtn9aw5O3uuyFuI
                                MA8GA1UdEwEB/wQFMAMBAf8wDQYJKoZIhvcNAQELBQADggEBALlUZCtYcNTzBjjQ
                                twPxBdMaLEbJKJvoE0sx1x1bOicJcimt3w3fgEIpmsCB9sTEEzEeJyRkgIrTTr6Y
                                f0YhoIkM/O12JWsB+aIdS8L3O09DXksoV7TMAwAHaoIaRU64dg63kti2xy2ZOoFZ
                                EglGoXevN23jkIdMl9ChiNwQEJWVbenU7QfdWsyWBcsqA6SKsXft7BKAqtKB3E+j
                                ibkzcfoqxQV2++wgPBATOl/amsFnuvrO0mvgdOtArM0vdPSiifRfxfMPx8+Jvxhq
                                vGKXrwJjc/Ihv6GR12lgVwsHoQnG74RcMZgZwh+1i5lgD/9o+JNhb91F5WK1F4pF
                                aS9kiMk=
                                -----END CERTIFICATE-----
  tls.key: |
                                -----BEGIN PRIVATE KEY-----
                                MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQDeBB1IN+IhVArJ
                                bbhlaVDa6fiCg+D1PFbLNwdUntyOY30ZrFpP5IBUxI/M9iWtXJa9XCugyQ6lT+8s
                                /krgjMvzs95BxH85/u6kpy/oCaVvoRg0VlOkBomaykSBSO8mxrB+CdyPiinlrdXy
                                DuSt469FwAIp6aDUZcIKi/MluD7YRIOpub6BHqwHIHnxpSqr7sCrCTDAhZbZ45tp
                                z/Abv34uqRvwwvVsrmuktipxg8Q5hwRJ8fo5eks+hZFBzIiO7H36ArS1FQCa+9mP
                                mH8onywjpRyfBSJzv7qBFPgZi+JuLni0LtTfV3PuSuLt/1Ijt6GdztrqwS9YxUGW
                                TiCcZ1nFAgMBAAECggEBANVQLrJMv0A2d4bBnQITBlTPqK39+A6oQtxNqwVq/Y7x
                                mCkqqDtK2OKZWXEcr2a6JzsZa/G4PBIpkywvx9Gode1ZTJr0KSmX/8LDwAu5+PIg
                                XhkrOIHIpj3LSbbOVLl0/e6bmwdvQIIlXAKOvLk2ohjqOyn6B0UL4Dwx6xS6yecP
                                YzIKjbxwt/PHTbbczpXnNgMfRMFCBnxBUVUc7/tCdliMaIfmkj5yxqnp36aiHIBW
                                GwGEkZHzTY5h4NWRlRz1lY9bE+N1CsbTSh8mJh1va3/0Zm3uh64kXwun8CCJ2Pod
                                4erGKRqF58vZUKi/5dhisj2LaoUPfRHKbIX/T+akwwECgYEA7p7p4yNnfZHr7LaX
                                FddNK4kxAbxgWI+qqAB5VQcKyORwgDzhbnps2FIX1OMgEG9lgM2zgcfKX/OqkNoP
                                BKR1QbCT9jsTomgCuUaNSxWWOnDjeyF/Ngw06GeAUCQ3uw+vZafSKX1Zs7XMK4Tu
                                QWXWncQioipSfWH7MyAwVJsR4O0CgYEA7i+bM2Gf8O+QuEzu5poxlb2dej49NwLt
                                /eQHEBIPvNLHtiClem+/ZE5KYdkwRLVm+OZwJ8HGbZQaVHNfzSq5Hqtkx0Oe5B59
                                mCkaiJdBwrP1zn6kLlACt5/50wTNZhe6UUwkYupey16TnIEZl689ok73KGPTvXCg
                                wd1VW3JFuTkCgYBSuFY+PmS+/Bn8SmPf125SHFIX1vTTXqJ7cQaeuj073S0+11wS
                                z2/yIatPSpkv+V4Ho8eJwvfeAXtskZtJMbXQWuVAI8SvtTzUe6e5krcsdTv20Gro
                                Ep04v8CUh6mmOE7Gf8H0ThcNnIU1xPRPSX133alf7CoCezf4xjza55LwFQKBgCcC
                                6RqbTMT7l+p3v1FJxAFQkzBobUJLWouRA48gRi+ZHli4NCI/l0tof0pTdlJqm7j8
                                lTYNyOA9t6pJU1GZQ8TAMbtpWebnD48SfGQO0hh/vSzbFSz4sdk9fH+Rc8ra7AtQ
                                u0zwMiKBFRA3HOf5LdEdueGFqDKI9euKwuY9ayoRAoGAC0blbz4eUn785c4TgdXp
                                pw2o+c5B0T1rn5MyW+gkNxdz9oXZO4nnOl3jhR1KG2b05LnlhUULvGtleclr7ESO
                                u9REJsw7fCP9ENZZ/CYB0vzzhcgesqwc69WLUX2LmKu/ggcjh5wY74JUMCYI8A6K
                                6Mg8bv5GFoDlIukPdQSYucI=
                                -----END PRIVATE KEY-----
---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: ca-issuer
spec:
  ca:
    secretName: ca-key-pair
---
# define a CA to sign certificate
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: self-htc-issuer
spec:
  selfSigned: {}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: htcondor-tls
spec:
  # Secret names are always required.
  secretName: htcondor-tls
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  subject:
    organizations:
    - infn
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ .Values.master.hostname }}
  isCA: False
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  dnsNames:
  - {{ .Values.master.hostname }}
  - master.{{ .Release.Namespace }}.svc.cluster.local
  - "schedd.{{ .Release.Namespace }}.svc.cluster.local"
  ipAddresses:
    - {{ .Values.master.publicIP }}
  # Issuer references are always required.
  issuerRef:
    name: ca-issuer
    #name: self-htc-issuer
    kind: Issuer
    #name: letsencrypt-staging
    #kind: ClusterIssuer

{{- end }}
