{{- if .Values.schedd.enabled }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: spool-pv
  labels:
    type: local
spec:
  storageClassName: {{ .Values.schedd.persistence.spooldir.storageClass }}
  capacity:
    storage: {{ .Values.schedd.persistence.spooldir.size }}
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-role.kubernetes.io/master
          operator: In
          values:
          - "true"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: spool
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: {{ .Values.schedd.persistence.spooldir.storageClass }}
  resources:
    requests:
      storage: {{ .Values.schedd.persistence.spooldir.size }}
{{- end }}
